# Site settings
title: Arctic Climate
email: staff@arcticlcc.org
description: > # this means to ignore newlines until "baseurl:"
  Addressing climate-related issues like melting permafrost, coastal erosion,
  subsistence hunting and gathering, food security, and freshwater resources is
  becoming increasingly important - both in the Arctic and Alaska at large. The
  resources provided here by the five Alaska Landscape Conservation Cooperatives
  highlight efforts to document and address these issues.
baseurl: # the subpath of your site, e.g. /blog/, leave empty for sub-domain
url: "http://climate.arcticlcc.org" # the base hostname & protocol for your site
github_username:  arctic-climate

# Build settings
markdown: kramdown
sass:
  style: compressed
